EJERCICIO 2
----------------------------------------------------------
"""

Ejercicio 2
Matrices:
A = [[1, 0, 2], [2, 1, 1], [3, 2, 0]]
B = [[0, 1, 1], [1, 2, 0], [2, 1, 3]]

Calcula A × B.
Calcula la traspuesta y determinante de A.
Vectores:
u = [2, -1, 3]
v = [1, 4, -2]

Calcula el producto interno u·v y determina si son ortogonales.
Calcula el ángulo entre u y v.
Derivadas:
g(x, y) = x*2 * y + sin(xy)

Calcula las derivadas parciales ∂g/∂x y ∂g/∂y.
Evalúa en el punto (x=1, y=π/2). """
Nombre del estudiante:
Javier Bravo


In [1]:
# ===========================================
# INTELIGENCIA ARTIFICIAL - EJERCICIO 2
# Alumno: Javier Neicer Bravo Macias

import numpy as np
import sympy as sp

# ---------------------------
# MATRICES
# ---------------------------
A_np = np.array([[1, 0, 2],
                 [2, 1, 1],
                 [3, 2, 0]], dtype=float)

B_np = np.array([[0, 1, 1],
                 [1, 2, 0],
                 [2, 1, 3]], dtype=float)

# A x B con NumPy
AB_np = A_np @ B_np

# Transpuesta y determinante con SymPy (para resultado exacto)
A_sp = sp.Matrix(A_np)
A_T_sp = A_sp.T
detA_sp = A_sp.det()

print("=== MATRICES ===")
print("A x B =\n", AB_np)
print("\nTranspuesta de A =\n", np.array(A_T_sp.tolist(), dtype=float))
print("\nDeterminante de A =", detA_sp)   # 0 → matriz singular

# ---------------------------
# VECTORES
# ---------------------------
u = np.array([ 2, -1,  3], dtype=float)
v = np.array([ 1,  4, -2], dtype=float)

dot_uv = float(u @ v)
norm_u = float(np.linalg.norm(u))
norm_v = float(np.linalg.norm(v))

# Ángulo (en radianes y grados)
cos_theta = dot_uv / (norm_u * norm_v)
theta_rad = float(np.arccos(cos_theta))
theta_deg = float(np.degrees(theta_rad))

print("\n=== VECTORES ===")
print("u · v =", dot_uv)
print("¿Son ortogonales? ->", "Sí (u·v = 0)" if dot_uv == 0 else "No (u·v ≠ 0)")
print(f"||u|| = {norm_u:.6f}   ||v|| = {norm_v:.6f}")
print(f"Ángulo(u,v) = {theta_rad:.6f} rad  = {theta_deg:.6f}°")

# ---------------------------
# DERIVADAS PARCIALES (SymPy)
# g(x, y) = x^2 * y + sin(x*y)
# ---------------------------
x, y = sp.symbols('x y', real=True)
g = x**2 * y + sp.sin(x*y)

dg_dx = sp.diff(g, x)
dg_dy = sp.diff(g, y)

# Evaluación en (x=1, y=π/2)
val = {x: 1, y: sp.pi/2}
dg_dx_val = sp.N(dg_dx.subs(val))
dg_dy_val = sp.N(dg_dy.subs(val))

print("\n=== DERIVADAS ===")
print("∂g/∂x =", dg_dx)
print("∂g/∂y =", dg_dy)
print(f"∂g/∂x(1, π/2) = {dg_dx_val}")  # ≈ π
print(f"∂g/∂y(1, π/2) = {dg_dy_val}")  # = 1

# ---------------------------
# SECCIÓN DE NOMBRE (requerida)
# ---------------------------
print("\nNombre del estudiante: Javier Neicer Bravo Macias")


=== MATRICES ===
A x B =
 [[4. 3. 7.]
 [3. 5. 5.]
 [2. 7. 3.]]

Transpuesta de A =
 [[1. 2. 3.]
 [0. 1. 2.]
 [2. 1. 0.]]

Determinante de A = 0

=== VECTORES ===
u · v = -8.0
¿Son ortogonales? -> No (u·v ≠ 0)
||u|| = 3.741657   ||v|| = 4.582576
Ángulo(u,v) = 2.056205 rad  = 117.811843°

=== DERIVADAS ===
∂g/∂x = 2*x*y + y*cos(x*y)
∂g/∂y = x**2 + x*cos(x*y)
∂g/∂x(1, π/2) = 3.14159265358979
∂g/∂y(1, π/2) = 1.00000000000000

Nombre del estudiante: Javier Neicer Bravo Macias
